### ISSUE TITLE
pages revealed before transition completes

### ISSUE THREAD

**Issue by wooogz** [gmrchk/swup#11]
maybe I'm understanding the use case incorrectly, but should the css animation always complete before it reveals the new page?

for me, especially when the pages are cached, the css transitions are completely skipped.

great work btw, a pleasure to use so far

**Comment by gmrchk** [comment]
Thanks!

Yes, the animations should always complete before the new page is revealed. It's possible you have an older version, where swup had a bug and the end of the transition of elements inside of your animated element was detected as the end of transition of the parent element. The latest version does not have this issue.

In case that update doesn't help, please provide your code or demo.

**Comment by carlfmichel** [comment]
Was there any resolution to this issue. I am having a similar problem. The transition works the first time but after the page is cached the transition is ignored. Any insight would be great!

I second the compliment, Swup is great!.

**Comment by gmrchk** [comment]
Thank you! 

From my experience, those symptoms indicate that it's not swup issue and you are most likely making mistake somewhere in you code. Unfortunatelly, that means I cannot help you without seeing your code or demo.

Can you please provide that?

**Comment by gmrchk** [comment]
I've seen people making several mistakes when getting this kind of behavior:

1. Using CSS `@keyframes` + `animation` property, instead of `transition` property + defining different styles in the transition state. CSS `animation` can be used for animating elements in the transition, but it cannot be used for swup's timing. 

2. Using `[class^="a-"]` selector wrong. The selector selects any element whose class attribute begins with string 'a-'... in short, class `a-class and-other` is selected, but class `and-other a-class` is not.

3. Not having the same structure on each page - missing elements for swup to replace in certain pages.

Hope this helps. Closing. Feel free to reopen with demo/code example.
