### ISSUE TITLE
PhotoSwipe and Swup

### ISSUE THREAD

**Issue by elemention** [gmrchk/swup#111]
Hi Georgy!
First of all thx for swup. It's perfect!

But i have problem with photoswipe. When i entering page like "/gallery" and then opening photoswipe - url changing like "/gallery#&gid=1&pid=1" and all going perfect. 
But when i close photoswipe, url changing back to "/gallery" and page going hard reset. 

If i entering on page with "/gallery#&gid=1&pid=1" directly, opening and closing photoswipe all going normal and page not hardreset.

If disable photoswipe history module all going perfectly, but i need history.

What's going wrong? And how can fix it?

sry for bad english(

**UPD: lol, my bad, actually prepros make hardreset, sorry**

**Comment by gmrchk** [comment]
Hi @elemention and thanks!

It seems that PhotoSwipe creates a new history record with `pushState` and calls `history.back()` when closing the gallery to get to the initial position in history. 

swup should react to this `history.back()` as the previous record (/gallery) was create by swup and swup will replace the content to the same content that is on the page (which is not necessary, but also shouldn't cause any issues except for possible undesired page transition to the same page). 
This behavior can be also modified with the [skipPopstateHandling option](https://github.com/gmrchk/swup#skip-popstate-handling) which accepts the popState event and returns boolean of whether swup should process the content replacement or not. This function is there specifically to solve any issues created by another library modifying browser history apart from swup. 

However, if your page does a "hard reload", it doesn't seem that swup is the problem here, as the only situation swup triggers hard reload is when the server error is encountered.

**Comment by brandlewco** [comment]
I'm having this same issue with photoSwipe and seem to be unable to skipPopstatehandling. how do I set event.state and event.state.source to prevent  the history.back() refresh from closing the gallery?
