### ISSUE TITLE
Post Request Issue

### ISSUE THREAD

**Issue by barisyild** [gmrchk/swup#115]
```javascript
swup.loadPage({
     url: `/upload.php`,
     method: "POST",
     data: {simplePost: true, _token: "secretToken"},
});
```

This post is sending '[object Object]' data.

I tried parse object as url variable but content-type variable is still 'text/plain;charset=UTF-8'

**Comment by gmrchk** [comment]
The `data`  is actually not a plain object, but rather a `FormData` object.

[This](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Sending_forms_through_JavaScript) page will give you more info on creating or sending the `FormData`. swup uses the following to send forms.

```javascripts
let form = event.target; // the form element
let formData  = new FormData(form); 
```

**Comment by dougkeeling** [comment]
I am having a similar issue when trying to send `GET` data.  I was happy to find this post and see that the plain objects aren't supported, but I'm still having problems with the following code:

`
data = {topic: "test"};

var formData = new FormData();
for(var key in data) {
    formData.append(key, data[key]);
}

swup.loadPage({ 
    url: "/search",
    method: "GET",
    data: formData,
});
`

If I understand things correctly, my FormData var should be set up appropriately, however, the `GET` string is never appended to the URL.  I would expect to see `/search?topic=test` but instead I just get `/search`.

**Comment by gmrchk** [comment]
I understand your confusion because I've been there some time ago. When sending the GET request, the URL of the request is what matters, not the request data, which makes sense when you think about how the GET requests work... 

However, I haven't found any "native" way to serialize the form into the URL format, and so, swup [builds the URL manually](https://github.com/gmrchk/swup/blob/33367a1072f8b5ebc646d7e0ca338a811b53a41d/src/index.js#L394-L423), before appending it to the value defined in form `action` attribute and sending the request.

If you do find some better way, please, let me know. :)

**Comment by dougkeeling** [comment]
@gmrchk Thanks for that link to the code!  Looks like it's just building the string then doing a regular `loadPage`.

So — correct me if I'm wrong — there's really no reason for me to even bother trying to build the FormData for a `GET` request, right?  If I have all the data I need to send, I should just build the string myself and do:

    swup.loadPage({ url: "/search?topic=test" });

**Comment by gmrchk** [comment]
Yep
