### ISSUE TITLE
Show page only when everything is loaded

### ISSUE THREAD

**Issue by MartDSam** [gmrchk/swup#118]
Hello @gmrchk

I'm doing a project in which some pages have enough images and some have videos. When the person first accesses the page I have a loading screen that waits until everything is ready. But when I go to a page using SWUP I do not have this control, so the page loads before everything is ready.

I tried to use the pageLoaded event, however it does not expect the media files to be loaded. Is there a way I can implement so that the content is shown only when everything is already loaded?

This "problem" occurs only when the internet is slow. I did the tests using chrome, in the network tab you can choose the speed of navigation. Putting 3g usually takes a few files longer and this ends up harming the transition animations on the pages.

I do not know if this is a bug of the pageLoaded event or it expects only the document to be ready and not all the files. I do not know if it would be possible to implement something that simulated window.onload.

Thank you very much!

**Comment by alcantara** [comment]
Try this instead of `pageLoaded` #38.

#11 animations always completes the animation before loading the page.

hope this helps.

**Comment by MartDSam** [comment]
@alcantara  Thanks for answering me.

I'm using SWUPJS with animejs. All works perfectly, the real problem is that as the SWUP does not wait for the media to be loaded the content is exchanged with the images still in loading. Already if the person accesses the page directly other than through SWUP the page is only shown when everything has been loaded using the onload event of the window. (window.onload). 

The animations work correctly, however as the SWUP does not wait for the images to be loaded, the animations occur with the still loading images.

**Comment by gmrchk** [comment]
Hi guys,

Yes, `pageLoaded` event is only called on the initial load of the page. There are ways to do the same when swup is transitioning, but it's a bit more tricky. 

For example, you would have to manually detect load event for all the images in the next page and wait for them before calling the `next` method in your animation. This can be done with some promises and `onload` event of `Image` object. Something like this should work:

```javascript
var loading = new Promise((resolve, reject) => {
    var img = new Image();
    img.onload = function() {
        resolve();
    }
    img.src = '/image/src/content.png';
}
loading.then(() => {
    // image has loaded
});
```

You can loop through images taken from swup cache and wait for all of them to resolve with `Promise.all([array of promises here])`.

BUT

I do not recommend this at all, not even on the initial load. Instead of giving the user with slow internet somewhat better experience by enabling preload and just not letting browser to do the hard reload, you could completely ruin it by not displaying any content at all (or taking a very long time to display any content). 

Instead of going that way, I would suggest digging into preloading assets. It seems that chrome preloads images by simply making a request to the page that contains a reference to the image (so enabling swup preload or calling swup `preload` method with expected next URL manually should help a lot on its own). Another way would be to append a hidden `img` tag to your page with `src` of the image you wish to preload. That should be enough to make browser preload the image.  

Making your page layout disposition not dependent on the images can also do a lot of good. Define the size of the images with height/width or make the page reserve the space for the images with any other responsive solution. This way your content at least does not jump around while the images are being loaded.

If you do actually go with waiting for images to load, I would at least implement some kind of limit for the waiting.

**Comment by MartDSam** [comment]
Thanks for the reply @gmrchk 

I thought about this choice of images, but I did not know if it was a good practice on coding issues. But as you exemplified yourself, I think it can be a viable option.

I know that taking too long can make browsing as bad as loading pages without being prepared.

However, usually a loading screen ends up slightly lessening the impact of the loading delay.

I used the lozadjs library for lazy load of the images, so I would expect loading only the images that are appearing on the screen.

Thank you for your help. I'll see what I can do.
