### ISSUE TITLE
Detecting Changes

### ISSUE THREAD

**Issue by AugmentBLU** [gmrchk/swup#128]
Hi, I have a script that detects changes to a form within a page and will warn the user if either refreshing or attempting to navigate away that the form needs saved. 

For some reason, I can't get this to work with swup links. I've tried the `clickLink` and `animationOutStart` events, neither are working as expected. I can get a confirm modal to appear but if clicking cancel, it still carries out the transition to the intended page, rather than stopping the event.

Could you give some pointers how this could be achieved? Thanks!

**Comment by gmrchk** [comment]
Hi, sorry for late reply, 

The event included in swup events are native events (like click), so if you tried running something like `event.preventDefault()` on those, it won't have any effect on swup process. 

This is a tough one actually. You could set swup [linkSelector](https://github.com/gmrchk/swup#link-selector) option to something that just doesn't fit any link. Then register another global link click event listener, which would check if the form needs to be saved and would use `loadPage` from [swup API](https://github.com/gmrchk/swup#api) to navigate to other pages. However, swup does a [lot of stuff](https://github.com/gmrchk/swup/blob/33367a1072f8b5ebc646d7e0ca338a811b53a41d/src/index.js#L275) before even calling that function after the click of the link happens, so that could introduce some problems.

I would suggest a bit of a different approach. How about saving the data filled in a form on swup `clickLink` event to the localStorage, and restoring the data on the next visit, so you don't even bother the user with a question? In case he does want to change the data, he can always rewrite it. There might be some issue with privacy and localStorage which you might want to look into, but I believe there isn't.
