### ISSUE TITLE
Varying elements replaced

### ISSUE THREAD

**Issue by richgwil** [gmrchk/swup#133]
Hello, 
awesome library. am loving it so far.
I'm having difficulty figuring out how to replace different elements for different pageLoads, or indeed if this is possible.
swup initialised with 
  elements: ['#main__wrap','#hdr-crt-lnk']

works fine for all links.

however, i do a custom pageLoad for form submission where I set 
  elements: ['#contact--form']

As I only want to replace the form on submission.
all works as expected apart from the new form content is loaded into #main_wrap instead of #contact--form.

I hope this makes sense. I'll continue you to investigate (read fiddle & play) to see if i can figure it out, but any assistance would be greatly appreciated.

thanks in advance
cheers
gwil

**Comment by richgwil** [comment]
have found a way to do this in the form submission handler by destroying Swup instance, reinitialising Swup with elements: ['#contact--form'] and adding a listener for swup:animationInDone where i destroy Swup again and reinitialise with elements: ['#main__wrap','#hdr-crt-lnk'].
It seems to work fine, but am still wondering if just changing the elements option on running instance should work or not. 
It works for scroll: false/true, as mentioned in docs.
Am i missing something?

**Comment by drivebass** [comment]
Hi @richgwil ,
This sounds interesting since swup doesn't handle different elements per page load.
Have you tried to just change the elements with the options function as per docs swup.options.elements = ...
Another suggestion would be to use a different animation to just hide the form by adding a data attribute data-swup-transition for the specfic case and reveal it on contentReplaced
Just some ideas

**Comment by richgwil** [comment]
hello @drivebass,

thanks for the input.

i had missed the popstate issue, and you are right, it get's totally confused by the destroy/reinit. bugger.
thankyou for that.

yes, i've tried simply replacing the swup.options.elements, it half worked as it loaded the new content but put it in the first container from the original swup.options.elements.
I'm not sure if it was something i was doing wrong but couldn't get it to load in right container.
It would be cool if it can/could be done by modifying the swup.options.elements on the fly. 

I played around with different animation options but couldn't get what i needed (i run validation on form before submission, display pop up messages on succes/failure etc), and all my lazyloading was being reset etc.

I'll play around somemore bu I think maybe i'll just use something else for the form submission.
cheers

**Comment by drivebass** [comment]
Maybe you could repeat destroy and reinit on Popstate too but I don't see it as an elegant solution. 
Any chance to work with FORM_SELECTOR: 'form[data-swup-form]' have you tried that?
I think the most elegant solution would be with a data-swup-transition attribute but it depends on the kind of form. 
Maybe plain ajax could work fine as a last result for the sepcific case.

**Comment by richgwil** [comment]
ok, what i've done now is utilise loadPage for the form submission. 
prior to calling loadPage:
1 - remove the data-swup on the original swup.options.elements
2 - reset swup.options.elements to the new elements
3 - add data-swups to the new elements 
4 - call loadPage with callback on swup:animationInDone
in callback:
1 - remove data-swup on new swup.options.elements
2 - reset swup.options.elements to original
3 - add data-swups to these

as far as i can tell this is working and keeping popstate happy.

it seems that this should be quite an easy mod for Swup, without breaking anything, and i would find it useful.
I'll post any further updates...

**Comment by drivebass** [comment]
Hi @richgwil ,
So for the specific case you manually define new elements and revert everything back to normal when complete. Sounds interesting. 

I ended up using a different transition for the specific case. 
Using loadPage like this:
```
swup.loadPage({
    url: "/someRoute", 
    method: "GET", 
    data: "html"', 
    customTransition: "form-results"
}); 
```
Then in my css I just add a tranisition to a form-overlay absolute positioned div over the form like this:
```
.form-overlay{
       position: absolute;
       width: 100%;
       height: 100%;
       opacity: 0;
       pointer-events: none;
       transition: opacity 0.3s ease;
}
html.to-form-results.is-animating .form-overay {
	opacity: 1;
}
```
Now when the form is submitted all original elements get replaced but what you actually see is the form transitioning and then updated when content gets replaced.

**Comment by gmrchk** [comment]
Hey guys, I can see you've done some nice experimenting here, good job!

Changing the `elements` option on the go doesn't currently work, but will work in the next version. This is primarily because swup saves the content of containers of the page into cache directly, so it doesn't have to find containers on each content replace. In the case of changing the option on the go, the containers will be replaced into a wrong place, as @richgwil already found out. 

In general, you shouldn't really need to replace different blocks of the page for different transition, it kind of goes against the idea of being an enhancement of a static site. 

I think @drivebass's solution with a custom animation for form submission is brilliant and a way to go here. You can still be replacing the whole page even for form submission, and it shouldn't matter that only a part of it changes. As long as you animate the form only, a user won't know that the rest of it was replaced as well. 

Alternatively, you can always go for a custom/plain ajax submission of form (I usually have). Swup form support is rather intended for submission of forms that affect a whole page, like "search on this web" kind of forms, where the animation of the whole page makes sense... but again, it never occurred to me to just modify the animation by using `loadPage` with `customTransition` parameter as @drivebass did.

**Comment by gmrchk** [comment]
I think the conclusion here is that changing different blocks for different transitions is a wrong way to go. The URL should always reflect whatever is on the page, even when you visit the page of the website from outside. That means that the containers defined in swup should replace any content that could be different at some page. The visual part of it, where we might need to make an illusion that only part of the page is being replaced can be done with custom transition.

I will close the issue at that but feel free to continue the conversation.

**Comment by richgwil** [comment]
hi @gmrchk & @drivebass,
thanks both for all the input. been away a while.
I eventually went with an ajaxy solution. the problem i was trying to overcome was re-loading of lazyloaded images on other reloaded parts of the page.

I have a slightly different issue and would appreciate any insights/ideas:

1 - I have a multi-language site
2 - It has a language specific css only rotating testimonial block
3 - The testimonial block should only be updated on page load & if the language is changed (via a link)

the whole site is working perfectly, with the language switching being swupified as well, I just can't seem to figure out a way to do the once only testimonial switch. I'm sure i'm missing something obvious (even if it's "don't do this with swup").

@gmrchk, you mentioned above that the containers would be variable in the next version, is this the case with 2.x?

thanks again,
cheers, gwil

**Comment by gmrchk** [comment]
I think you're trying to solve a problem that is not really there in a first place from a UX perspective. Changing a language is most likely going to be done once by a user, right after entering the site. The user would usually start browsing the site after changing the language, where the swupified site (nice term btw :thumbsup:) would be presented in the way we want it, and changing of language would be done with a normal browser reload once "before we start the experience". Of course, I'm not sure about the exact use case, but language versions can have different navigations, analytics and more, that the site normally has common for all pages. It just seems like too much effort for no good reason. 

If you still decide to go with the dynamic swupified version, I would try to check for `lang` attribute on html element (or anything that defines language versions in your site) on `contentReplaced` event, and replace the testimonial manually in case the language has changed. You can get the current testimonials block from `cache.getCurrentPage().originalContent`.

Containers option cannot be changed when swup is already running. I thought it would be a nice addition at one point, but decided against at the end for multiple reasons, one of which is that the page should work the same without swup (without JS), and that would be contradicting this fact, as we discussed earlier.

Two instances are theoretically possible, but it's definitely not something I would recommend or help with, as I've never tried it myself.

**Comment by richgwil** [comment]
Thanks for the response.
I totally agree with your reasoing. However, in this case I needed the language transition to match the normal swup page transition.
Used a little ajax in the end and all works as required.
Thankyou for swup and all your work, it's a wondeful tool/platform.
cheers,
gwil

**Comment by hirasso** [comment]
Hi @gmrchk , swup really is amazing, thank you so much for your work! I was playing around with a fragmented response, as well, and came pretty far.

My use case: On some of my pages I want to load certain responses into an overlay. These overlays have a dedicated URL, for example:
```
https://example.com/people/person/
```
Visiting this URL directly should display the overlay above my list of people. Calling it from `https://example.com/people/` should not load the full page including the people list, but instead just render the overlay. as @richgwil already pointed out, otherwise I would loose scroll state and also the thumbnails in my list would flicker due to re-loading them.

**This is the code that works for me:**

In my HTML templates, I introduced two new attributes: `[data-swup-fragment-placeholder]` and `[data-swup-fragment]`, for example:

```html
<!-- index.html -->
<p><a href="/overlay.html">Load Overlay</a></p>
<div data-swup-fragment-placeholder="overlay"></div>

<!-- overlay.html -->
<div id="overlay" data-swup-fragment-placeholder="overlay" data-swup-fragment="overlay" style="background: red;">
   This is a fragment
</div>
```

My code hooks into `willReplaceContent` and `contentReplaced` and does the following:

```js
const swupOptions = {
  containers: ['#page'],
  cache: true
}
const swup = new Swup(swupOptions)

let fragmentsReplaced = false
let originalBlocks = null

swup.on('willReplaceContent', () => {
  // initially set this to false, until we find some fragments in the response
  fragmentsReplaced = false;
  // save the current cache entry
  const currentCacheEntry = swup.cache.getCurrentPage()
  // save the current cache blocks so that they can be reset in 'contentReplaced'
  originalBlocks = currentCacheEntry.blocks
  // parse the html of the current cache entry
  const doc = new DOMParser().parseFromString(currentCacheEntry.originalContent, "text/html")
  // look for fragments in the parsed html
  const fragments = doc.querySelectorAll('[data-swup-fragment]')
  // bail early if no fragments were found in the html
  if( !fragments.length ) return;
  // save current [data-swup] elements
  const originalSwupElements = document.querySelectorAll('[data-swup]')

  const fragmentContainers = [];
  const fragmentBlocks = [];
  
  /** 
   * Cycle through all found fragments and look for matching 
   * placeholders in the current DOM. If there are any, 
   * create a block entry in the cache object and add the block's id to the options
   */
  fragments.forEach((el, index) => {
    const placeholder = document.querySelector(`[data-swup-fragment-placeholder=${el.dataset.swupFragment}]`)
    if( !placeholder ) return
    delete el.dataset.swupFragment
    placeholder.dataset.swup = index;
    fragmentContainers.push(`#${el.id}`)
    fragmentBlocks.push(el.outerHTML)
  })
  
  if( !fragmentContainers.length ) return
  fragmentsReplaced = true
  
  // remove [data-swup] from the original swup elements
  originalSwupElements.forEach(el => {
    el.dataset.restoreSwup = el.dataset.swup
    delete el.dataset.swup
  })

  // apply the fragment blocks to the cache entry
  currentCacheEntry.blocks = fragmentBlocks
  // update the cache
  swup.cache.cacheUrl(currentCacheEntry)
  // apply the updated swup containers option
  swup.options.containers = fragmentContainers
  
})
swup.on('contentReplaced', e => {
  // if we replaced fragments before rendering the page, 
  // reset the state so that popstate will still work as expected
  if( fragmentsReplaced ) {
    // reset the swup options to the original
    swup.options.containers = swupOptions.containers
    // reset the cache with the original blocks
    const cacheEntry = swup.cache.getCurrentPage()
    cacheEntry.blocks = originalBlocks
    swup.cache.cacheUrl(cacheEntry)
    // restore [data-swup] attributes
    document.querySelectorAll('[data-restore-swup]').forEach(el => {
      el.dataset.swup = el.dataset.restoreSwup
      delete el.dataset.restoreSwup
    })
    initFragmentView()
    return;
  }
  initPageView()
})
```

This solution works nicely, even if I navigate away from my overlay to somewhere else on the page and press the back button later.

**Comment by daun** [comment]
@hirasso Nice. Looks like a great solution to a common problem. Do you happen to have an example of a site that's using this? I've been meaning to tackle something like this for a while but have never come around to it.

**Comment by hirasso** [comment]
I created a proof-of-concept plugin as a starting point for discussion: https://github.com/hirasso/swup-fragment-plugin
