### ISSUE TITLE
Animate element from one page to new position on target page

### ISSUE THREAD

**Issue by blimpmason** [gmrchk/swup#17]
I'm just wondering how you'd recommend achieving this type of effect with swup (this example is coded with barba.js but I'd prefer to be using swup):
http://swup.grossdevelopment.net/

Would the 4 images on the index page need to exist outside of the page content container that SWUP replaces and thus remain in the DOM across all pages? Or is it best to detach them via JS, animate into new position (matching position of target page), and then destroy when the new page has loaded?

Another scenario could be to click a carousel slide on the homepage that animates into full-bleed hero image of the target page.

Also curious about this next/previous post example which slides the new page in while the old page animates out:
http://friendshop.com/work/family/

Thanks you!

**Comment by gmrchk** [comment]
Interesting question!

If the example is as it is and won't be dynamic at the end, it should be completely fine to take the images out of the replaced content and just have it on the page at all times. You will also save yourself a lot of trouble implementing, as this can be handled pretty well by classes used by swup. You would also get rid of the image "blinking", as those are quite big images and browser (I guess especially with retina, as I see the blinking on each content replace) can have trouble rendering it even when it's already loaded.  

However, if the images or the placement of the images is dynamic, I would probably create another fixed layer over the screen, which would only serve to recreate the clicked image with its size and placement and then animate it to the "stretched" position, where the new page would pop in. This should not be an issue, as the "future" position is known and common for all the images.

As you are animating large layers/images, I would suggest using JS library for that instead of CSS animation, as from my experience, JS can be much better at that, but I see you have already figured that (go GSAP!). GSAP can be very well used with swupjs. I noticed you are animating the large image with JS, while moving the small images with CSS. How about unifying that and using JS only? I believe it would add to the "smoothness" of the animation.

I understand that this is just an example, and you probably had those intentions already, but I would like to mention... 
That's a lot of JS to load at the first load (3.4Mb), just to show 4 images. Try to take advantage of webpack and load only what's necessary. Ideally, use code splitting for anything that is not needed at the time.
Also, maybe consider only loading thumbnails at first, and then preload the actual images after the initial render (simply appending image tag with that source should be enough for the browser to cache the images), while a user can look around and doesn't have to wait for 4 large images to load when it's not necessary.  


**For the second example:**
Swup, as it is, doesn't support having both pages on the screen at one time as it is shown here, because that would mean waiting for the next page to load to do something, but... with some quick fade (like .3s) combined with that movement to the side (ideally with some easing), I think the effect could be almost recreated and look pretty neat as well. 

While we're at it, there is almost no content on those pages, so I would probably go for a custom solution which would load the contents of all pages in some json like format (or it could be already part of each page in footer or something...) and solve the rest including browser history manually. This would help with the issue of waiting for the load and you could prepare those video containers ahead of time, to avoid the waiting for the player to load on each screen. 

Thoughts?

**Comment by blimpmason** [comment]
Thanks so much for this considered response! I'm marking this as closed but will respond more when I've had a chance to experiment with these suggestions.

**Comment by mileyvirus** [comment]
Hey @blimpmason 👋 
Did you eventually manage to do it with swup instead of barba?
