### ISSUE TITLE
Yarn Package missing /dist

### ISSUE THREAD

**Issue by MikeHarrison** [gmrchk/swup#29]
When I add Swup through Yarn (`yarn add swup`), the package I get is missing the `/dist` folder. The folder tree I get is like:

```
swup
|- .idea
|- lib
|- plugins
```
And there is no swup.js present. Wierd one! Am I downloading the wrong package or is this an error?

**Comment by gmrchk** [comment]
I'm going to explain some concepts that are used in swup file structure, so we're on the same page. 

When getting the package through Yarn or NPM, you get a package published on NPM. 
The `package.json` file includes a line `"main": "lib/index.js",`, which tells NPM that this is the root file, so when you do `import Swup from 'swup'`, this is the file you're getting. Actually, this is only a root file of swup which imports all other parts it needs from *lib* folder, so basically what you are loading is the whole *lib* folder. *lib* folder is a copy of *src* folder and is transpiled by babel, so people can load it from NPM and doesn't have to transpile it again. 

Plugins folder is in the root so the plugins can be loaded like this `swup/plugins/pluginName`. This folder is in the root only because NPM does not allow to define root folder, which in this case, would be `lib` and loading plugins as `swup/lib/plugins/pluginName` just seems too ugly. 

`dist` folder is already bundled code ready for browser, that's why it can be included in a script tag. 

NPM similarly to GIT has a [.npmignore](https://github.com/gmrchk/swup/blob/master/.npmignore) file which, in this case, includes dist folder, so it is not published in NPM, as it is not necessary because all you need is in lib folder which is accessed when you do the `import Swup from 'swup'`.

---

Now, when people use a package manager like Yarn or NPM to get packages, I assume they are using some bundler to bundle it all together, and not include the bundled file in script tag from `node_modules` folder (or at least I never met anyone who does). That's why it's not included in the NPM package and only present here on Github where people can download it if needed. Do you load scripts from `node_modules` folder via script tag? There is no problem to add it. I just always thought it's unnecessary and wouldn't be used. 

PS:
`.idea` is folder used by my IDE and shouldn't be in the package. I have deleted it. Thank you for pointing it out.

**Comment by MikeHarrison** [comment]
Hi,

Thanks for taking the time to explain, I appreciate it :)

Perhaps my workflow is a little odd! I have my `node_modules` folder, and use Yarn to add / upgrade / delete packages within it.

I use Codekit for my build process, which has the facility to import javascript files into one source file, which is then minified on build. So I pull any node_module files I want into that, add my own javascript and then build. This is why I could do with the `dist` file being available, to be used for importing. More about how that Codekit bit works here: [https://codekitapp.com/help/javascript/](https://codekitapp.com/help/javascript/) 

I can of course download it from github (which is what I will do for this project), but then I miss out on the easy upgrade of the package when changes are made.

**Comment by gmrchk** [comment]
No worries. Kind of used it as an opportunity to describe it for future reference. 

I see... I have added the dist folder to npm, as it's few extra files (relatively small) but will allow better management for people with similar workflow to yours.
