### ISSUE TITLE
Event Listener & document load conflict

### ISSUE THREAD

**Issue by Ehmo6152** [gmrchk/swup#31]
I have decided to reword this post because I noticed that my original post was very difficult to understand.

**Issue:** scripts don't work when swup loads a new page.

**Initial Solution:** Add an event handler as in the documentation of swup. Aas seen in Issue #2 

Problem with this solution is that if I go directly to a page url, it doesn't load the script, this is an issue as I have sliders on my home page that were originally initializing form page load, but now it is waiting for an event handler, but it doesnt find one when the page is initially loaded.

I hope that clears up this strange question.

**Comment by gmrchk** [comment]
If I understand correctly, you were running your code after load before implementing swup, but now you moved it into a swup event handler.

The issue you are mentioning (#2) was only about reloading the script after page transition, so it was once run at load by the developer elsewhere.  

But don't worry, swup has lots of [events](https://github.com/gmrchk/swup#list-of-all-events) you can use. Your problem should be solved by by changing the event to `swup:pageView `, which is the same as `swup:contentReplaced `, but is also once triggered on load.

**Comment by Ehmo6152** [comment]
oh perfect! `swup:pageView` worked perfectly for me. Thank you very much, but now some pages randomly only show the pageInAnimation and not the PageOutAnimation, even though they are both being loaded in the console. Its not a huge deal, but it does make things seem a tad choppy

**Comment by Ehmo6152** [comment]
Ok so what I thought was working, was actually some old cached version of my site. I dont know what happened, but I still am having the same issue as before with all my scripts. For example:

If you navigate to this page directly, it works great ->http://futsoc.co/about/other/by-the-numbers/

But if you go to the link of the same page in the nav bar (About>By The Numbers) it doesnt work.

I really want this so badly to work!

**Comment by Ehmo6152** [comment]
Also, when im on the home page, swup doesnt load any links I click and the colsol reads
![capture](https://user-images.githubusercontent.com/42647924/44828896-fc179880-abe7-11e8-9da2-07019b1c7b17.JPG)
:

**Comment by gmrchk** [comment]
I'm guessing the scripts you have in mind on page http://futsoc.co/about/other/by-the-numbers/ are the graphs. Those are initialized in the `script` tag in your HTML. swup replaces the content, but that doesn't mean it runs the code in `script` tags in that HTML, like [swupMergeHeadPlugin](https://github.com/gmrchk/swup#swupmergeheadplugin) can. You could, of course, use the same approach as the plugin does and run the scripts in the replaced content. 

I don't really like combining HTML with scripts tho, so I would recommend moving that code for graphs to whatever you are running on `swup:contentReplaced`, and wrapping it in some if statement which would check if the canvas with that ID is on the page or not. 

---

The problem you are facing on the homepage is different. The element that you use to cover up the page is not working on the homepage because it doesn't have any styles defined there, but does have on other pages... so swup is waiting on that element to finish animating, but it never even starts. Move that element outside of the `#swup` container and make the styles for it global.

You've done a good job of putting it all together, don't get discouraged by these little things... those just happen.

**Comment by Ehmo6152** [comment]
Ok thank you! I got the home page to work. I forgot to link the stylesheet, whoops.

As for the graphs, I moved them to a separate JS file as recommended and placed them inside the event listener swup:contentReplaced. It works great, but only if I access the page from the website, if I go directly to that page they dont load. I assume its because swup isnt replacing anything, but rather loading the page for the first time. I also tried swup:pageView, but that didnt work either.

I really appreciate all your help!

**Comment by gmrchk** [comment]
Sorry, I meant `swup:pageView`, that is once triggered on load as well. 

You are first enabling swup, which triggers the event, and after that, you are registering the event listener. Change the order of the scripts included in your page so the swup is enabled after the register of the event listener. 

No worries, at least we can refer to your questions in the future.

**Comment by Ehmo6152** [comment]
so reordering the pages seemed to work much better, but im getting a new problem.

✔️ Go directly to http://futsoc.co/about/other/by-the-numbers/
❌ Go to http://futsoc.co/ > then navigating to to /by-the-numbers/
✔️ Go to http://futsoc.co/ > then navigating to any other page > then navigating to /by-the-numbers/

Im not sure why this is happening but its really strange. I also get this error
![capture](https://user-images.githubusercontent.com/42647924/44920021-e5b72d00-ad0c-11e8-9293-c9417368abf5.JPG)

**Comment by gmrchk** [comment]
Those errors have nothing to do with swup really, but... 

1. You are running the script for charts even when it's not on the page. Wrap it in some code that would check that the element with that id (or whatever) exists.
2. I am guessing you were running the script for the charts (executed on `swup:pageView` event) before loading the library used in those Charts, or for any reason, variable `Chart` is not defined in your code. Maybe using `window.Chart` could help?

**Comment by gmrchk** [comment]
I will go ahead and close this as there is most likely nothing wrong with swup, but feel free to ask in case you're still having trouble implementing.
