### ISSUE TITLE
Internet Explorer / Edge - not working

### ISSUE THREAD

**Issue by DaveWoody** [gmrchk/swup#32]
Love your plugin! Everything works fine so far in Chrome and Firefox. Still i got a big issue. If i open my page in Edge swup will not work. The page is stuck in "is-rendering is changing" most of the time. 

I turned debug on. Hope you can help me.

Any solution? Am i missing something?

http://klug-bohren.sketch-lab.de/

**Comment by DaveWoody** [comment]
Okay so i fixed it with an event listener but still ... maybe i am missing something i did wrong.

My fix:
// Add event Listener after animation is done
`document.addEventListener('swup:animationInDone', event => { 
        // Check if class is-changing is still present
	if($('.is-changing').length == 0) {

	} else {
        // If yes remove both classes
		$("html").removeClass("is-changing").removeClass("is-rendering")
	};
});
`
Cheers!

**Comment by gmrchk** [comment]
Hi Dave,
I will check this within the next few days (don't really have Edge around) and get back to you. However, from your description, it looks the blame is on swup, or Edge really... Glad you found a quick workaround.

Good job on site!
Cheers

**Comment by gmrchk** [comment]
This is a weird one...

The function `startsWith` was used in swup for checking whether the class starts with "to-" substring, which EI/Edge doesn't support. 

Now the weird part...

After changing the syntax, no error was reported by IE/Edge, but the classes still didn't really work properly. While swup does change the values of `className` quickly in order, the order is correct. It seems that IE has some trouble keeping some values saved in memory up to date with the DOM, so even where it's showing the correct values, it doesn't work with correct values.

Following example might explain what I mean.
```javascript
console.log(String(document.documentElement.classList)); // outputs "class1 class2 class3 class4"

document.documentElement.classList.forEach(function(item) {
    console.log(item);
}); // outputs "class1" "class2" "class4" for example
```

In any way, fixed by using `document.documentElement.className` instead.
