### ISSUE TITLE
Waiting for loading animation to complete.

### ISSUE THREAD

**Issue by Riaan-ZA** [gmrchk/swup#38]
Im implementing a page load state which consists of a overlay that slides over the content and then slides out to reveal the new content. Hoverver swup is not waiting for this animation to complete, so it's effectively not showing at all (Im working on a local environment so load times are almost instantaneous). 

Even though the new page might be loaded before the loading animation shows or is complete, I still what the entire loading animation to play through.

This is my  current loader css:

```
.c-load-screen {
    width: 100vw;
    height: 100vh;
    position: absolute;
    top: 0;
    left: 0;
    z-index: 2;
    background-color: $orange;
    transform: translateX(-100%);
    transition: all 0.5s ease;
}

.is-changing .c-load-screen{
    transform: translateX(0);
}
```

Is there any way I can acheive this?

**Comment by gmrchk** [comment]
FYI - use `is-animating` for the animating state instead, otherwise the content wouldn't animate back in (or in your case overlay wouldn't slide out of viewport) in case swup did wait for the animation finish.

```css
html.is-animating .c-load-screen{
    transform: translateX(0);
}
```

But back to your problem. If swup doesn't wait for the animation to finish, it means it selects wrong/no elements that it should wait for.
Can you show your HTML for the overlay and swup settings?

**Comment by Riaan-ZA** [comment]
Thanks @gmrchk The loader element was outside of the `<main id="swup">` element. It improved when I added the '.load-screen' selector to swup's elements to watch, however it's only playing the out animation, the sliding in to viewport animation is not.

my css is now: 

```
.c-load-screen {
    width: 100vw;
    height: 100vh;
    position: absolute;
    top: 0;
    left: 0;
    z-index: 2;
    background-color: $orange;
    transform: translateX(-100%);
    transition: all 0.5s ease;
}

html.is-animating .c-load-screen {
    transform: translateX(0);
}
```
and my HTML:

```
<body>
<main id="swup">
    <h1>Features</h1>
</main>
<div class="c-load-screen"></div>
```
and JS:

```
const swup = new Swup({
    cache: false,
    debugMode: true,
    elements: ['#swup', '.c-load-screen']
})
```

**Comment by gmrchk** [comment]
swup has options `elements` and `animationSelector`. `elements` serves for defining the blocks of HTML that need to be replaced.  `animationSelector` serves to define what elements should swup wait for to finish animating. This is separated because replaced elements are not always the ones that are animating - your example is a perfect use case of this.  

This should make it work for you. 

```javascript
const swup = new Swup({
    cache: false,
    debugMode: true,
    elements: ['#swup'],
    animationSelector: '.c-load-screen',
})
```

**Comment by Riaan-ZA** [comment]
Thanks @gmrchk  for the clarification and the quick responses. That did the trick
