### ISSUE TITLE
Possible to wait for images on page to be loaded?

### ISSUE THREAD

**Issue by dougkeeling** [gmrchk/swup#43]
Hi there, I'm noticing that the page is transitioning in and some images on the page are still being loaded — so we're getting kind of an ugly "snap" when they suddenly appear.  

Would there be a way of waiting for those to load completely, or possibly using something like imagesLoaded in conjunction with Swup?  I wasn't sure exactly how that should be implemented.

**Comment by gmrchk** [comment]
Hi,

swup doesn't have that option, but let's call it a feature rather than a bug. The animation is an enhancement of static page to improve the user experience. Slowing it down wouldn't really improve it. [Here](https://github.com/gmrchk/swupjs/issues/4) is some previous conversation about it.

I would suggest trying to get your image sizes as low as possible (services like [this](https://tinypng.com/) can help with that), or even using formats like webp with fallback. 

Another option is to preload the images you know you are going to need (probably the ones at the top of pages) after initial load. Placing a hidden `img` tag into a DOM should be enough for a browser to make a request and cache the image. 

Some delayed animation for the image only could also help, and might even make the transition more "fun".

Cheers!
