### ISSUE TITLE
swupMergeHeadPlugin is stripping style tags also

### ISSUE THREAD

**Issue by isaac-martin** [gmrchk/swup#50]
Looks like when installing this plugin any style tags in head are not replaced on page load? Not sure if I am doing something wrong

**Comment by gmrchk** [comment]
I'm not really using the plugin myself, so I will have to test things out. For now, you could place your CSS in the separate loaded file and apply your styles only for certain pages using a class on `body` tag, which is replaced by swup for each page.

**Comment by gmrchk** [comment]
Hi @isaac-martin,

I tested swupMergeHeadPlugin and it works as expected for - when page content is replaced, it removes any tags that are not present in the head of next page and adds any that are in the head of next page, but not currently present. 

Can you describe your problem?

**Comment by isaac-martin** [comment]
Sorry I slept on this one. I ended up diasbling while we were doing development. Going to look tomorrow - but I think its because the style tags aren't referenced in the mergeHeadPlugin. 

If I can fix I will open a PR.

**Comment by gmrchk** [comment]
swupMergeHeadPlugin basically replaces the content of the whole head tag for each page, but does so without changing the tags that are already present on both pages. 

I guess that unusual behavior could be caused by not preserving the order of tags in some specific cases. Please, let me know how the debugging goes.

I know that the structure of styles is not always controllable, like in case of using some WordPress plugin for styling the page through the web admin, which will usually generate separate CSS files for each page/block. However, if you do have a control over your styles, I usually discourage people from loading separate files for each page (so from using swupMergeHeadPlugin). We're trying to give a website a bit more app-like feel with swup, and manually replacing styles/link/script tags in the document head doesn't seem like the way to go to me. If some styles need to be applied to only some pages, there is always a possibility of using [classes on the body tag](https://github.com/gmrchk/swup#page-class-prefix), which swup replaces during transitions.
