### ISSUE TITLE
Don't work on mobile

### ISSUE THREAD

**Issue by ronaldohoch** [gmrchk/swup#62]
Hello! You're awesome!

When i use mobile in Google Chrome Developer Tools, the plugin doesn't work, see the gif bellow.
It freezes and doesn't load the page

![mobile](https://user-images.githubusercontent.com/2287371/46737618-59d0e300-cc72-11e8-8e14-07eef82ae9ba.gif)

**Comment by gmrchk** [comment]
Hi!

it seems that you are missing some style for transition on mobile, so one of the animated elements doesn't animate, but swup waits for it to finish the animation. Could you look if the `swup:animationOutDone` event is fired when the page gets stuck? If not, this is most likely the issue.

**Comment by ronaldohoch** [comment]
Sorry for the delay.
The event didn't fire.

![gif_complete](https://user-images.githubusercontent.com/2287371/46826557-a8fb3e80-cd6c-11e8-90c1-2e163b9ee859.gif)

**Comment by gmrchk** [comment]
As you probably see, the first transition doesn't finish all the way (classes on `html` tag are not removed) and second get's just to the end of the *OUT* stage, because some element on the `case-omni` page doesn't have the animation defined, while still having `transition-*` class. In other words, styles definition for some `transition-*` class is missing in CSS.

The problem should be clear, so I'm not sure if you need some further help or you just didn't close the issue. Feel free to ask if something is unclear.

**Comment by ronaldohoch** [comment]
Hello @gmrchk, thanks for your answer, i put the css class and it doesn't working, see gifs bellow:
Desktop Working:
![gif_desktop](https://user-images.githubusercontent.com/2287371/46949043-6d0af680-d056-11e8-9abb-3ec31926fca1.gif)
Mobile Don't Working:
![gif_mobile](https://user-images.githubusercontent.com/2287371/46949061-7bf1a900-d056-11e8-8486-6373bd2dc8c6.gif)
