### ISSUE TITLE
Mobile Issue

### ISSUE THREAD

**Issue by ronaldohoch** [gmrchk/swup#66]
Hello @gmrchk, sorry but I couldn't reopen the previous issue.

Thanks for your answer #62, I put the css class and it doesn't working, see gifs bellow:

Desktop Working:
![gif_desktop](https://user-images.githubusercontent.com/2287371/46949043-6d0af680-d056-11e8-9abb-3ec31926fca1.gif)
Mobile Don't Working:
![gif_mobile](https://user-images.githubusercontent.com/2287371/46949061-7bf1a900-d056-11e8-8486-6373bd2dc8c6.gif)

_Originally posted by @ronaldohoch in https://github.com/gmrchk/swup/issues/62#issuecomment-429819530_

**Comment by gmrchk** [comment]
Hi,
can you post the CSS for your `.transition-*` classes?

**Comment by ronaldohoch** [comment]
https://pastebin.com/DWhqsEG6

**Comment by gmrchk** [comment]
I'm guessing your issue is on line 135, although I'm not quite sure why that would affect only mobile (unless an element with this class is only present in the DOM on mobile for some reason). The "hidden" state of the element with class `transition-right-out` is not defined (or is incorrect, so basically not defined for a browser), so swup waits for it to finish the animation, but it never even starts. 

Just FYI - you don't need to redefine the same `transition` property with `is-animating` class for elements. Also, (I use automatic prefixes, so I'm not 100% on this) but I'm pretty sure all of those prefixes (-moz-, -ms-...) are not needed unless you want to support some really out of date/barely used browsers.
