### ISSUE TITLE
Using `forEach` in a NodeList breaks in iOS 9

### ISSUE THREAD

**Issue by loup-brun** [gmrchk/swup#78]
Hi,

I'm testing a website using Swup on my iPad. Debugging shows that `forEach` is not a function when that method is tried on `querySelectorAll()`

It is important to note that `querySelectorAll()` returns a `NodeList`, not a native `Array` (although this works cutting edge modern browsers).

The workaround is usually to **arrayify** the NodeList, i.e. make an actual array out of it:

```js
var arr = Array.prototype.slice.call(yourNodeList) // yey!
```
Here's a screenshot of the Safari console error:

![swup](https://user-images.githubusercontent.com/9596476/48245264-fb556c80-e3b7-11e8-8172-fb8fd2370bd5.png)

The workaround for this

**Comment by gmrchk** [comment]
Hi @loup-brun, 

This is a pretty known issue, I don't know how I missed it. I guess most browsers just add that forEach functionality by default for some time. Thanks for reporting!

While I don't have a device I could test it with, I basically used your proposed solution, which is the same solution as is used in [Gia](https://github.com/giantcz/gia/blob/master/src/utils.js)... so should be fixed in the latest version.

In case the problem persists, please, don't hesitate to get back to me. 

Cheers
