### ISSUE TITLE
OwlCarousel and swup

### ISSUE THREAD

**Issue by gustavo-a** [gmrchk/swup#81]
I'm having some trouble making swup to work along with [OwlCarousel](https://github.com/OwlCarousel2/OwlCarousel2). Here's my problem:

I have this page with a carousel and when I go to another page and come back to this one my carousel is loaded with two additional items.

**BEFORE**

![image](https://user-images.githubusercontent.com/26806307/48848184-77718c00-ed8a-11e8-97bf-c5031cdbdb92.png)

**AFTER**

![image](https://user-images.githubusercontent.com/26806307/48848381-e6e77b80-ed8a-11e8-9095-5388257f2755.png)

Look how these additional items have dots inside them. 

Here's my js:

```
function loadOwlHome (){
  $('#home-top-slider').owlCarousel({
    items: 1,
    margin: 50,
    loop: true,
    center: true,
    mouseDrag: true,
    touchDrag: true,
    nav: false,
    rewind: false,
    slideTransition: 'ease',
    dots: true,
    autoplay: true,
    autoplayTimeout: 10000,
    autoplayHoverPause: true,
    autoplaySpeed: 300,
    //autoWidth: true
  });
}

loadOwlHome();

let options = {
    elements: ['#swup'],
    cache: true,
    preload: true,
    scroll: true,
    debugMode: true,
  }

  const swup = new Swup(options);

  swup.on('contentReplaced', () =>{
    $('#home-top-slider').owlCarousel('destroy');
    
    if($('#home-top-slider').length > 0){
      loadOwlHome();
    }
  });

```

I don't know what to do, this is driving me crazy. I don't even know if I should be posting this here or in OwlCarousel's repo.

**Comment by gmrchk** [comment]
Hi @gustavo-a,

My wild guess is that the problem lies in enabling the carousel before swup, while having cache set to true. That means that the page cached by swup already has an html structure modified by OwlCarousel, which (even if that's not the cause of the problem) isn't right.

If that's not the case, triggering some kind of resize event on OwlCarousel (and forcing the carousel to recalculate stuff) after **contentReplace** (with `setTimeout` I guess) could fix the problem.

Also, consider destroying the carousel on **willReplaceContent** event, as the html structure of the carousel is still in the DOM at that time.

**Comment by gustavo-a** [comment]
Thanks @gmrchk!

It worked!

I destroyed the carousel on **willReplaceContent** as you said. I also forced the carousel to refresh on **contentReplace** with `setTimeout`

**Comment by JamesGillen402** [comment]
Hey @gustavo-a 

Could you add your code here, I'm having a similar problem and struggling to get it working. My problem is that the carousel doesn't load back in (get triggered) when I navigate back to the page. 

Thanks,
