### ISSUE TITLE
Reloading JS scripts before content replace

### ISSUE THREAD

**Issue by dnnsjsk** [gmrchk/swup#83]
Hey there,

I stumbled upon SWUP and I love it! I am currently using it with Oxygen and WordPress, everything works wonderful so far, however, I can't get scripts to reload after the content gets replaced.

Following the example from here: https://github.com/gmrchk/swup/issues/41 - this is my code so far:

```
function init () {
gumshoe.init({
	activeClass: 'services-nav-link-active',
  	offset: 150
});
var scroll = new SmoothScroll('a[href*="#"]', {
	offset: 150,
 	scrollDelay: false
});
}

init();
document.addEventListener('swup:contentReplaced', init);
```

Hope someone can help me here, thanks!

Dennis

**Comment by gmrchk** [comment]
Hi @dnnsjsk,

Seems you're doing everything fine. Maybe you should consider destroying your instances before moving on to the other page. This could prevent the libraries from creating a new instance on the same elements. 

```javascript
document.addEventListener('swup:willReplaceContent', function () {
    gumshoe.destroy();
    scroll.destroy();
});
```

However, that's just my guess and I would look for a solution at the repo of those two libraries or if you have some live example we could check for you, that would be great!

Btw, swup has pretty neat [scroll control](https://github.com/gmrchk/swup#scroll) built in. You might consider trying to use that, instead of loading another library.

**Comment by gmrchk** [comment]
Hi @dnnsjsk, did you get any closer to the solution?

**Comment by dnnsjsk** [comment]
Hey,

I was focusing on other parts of development for now, I might revisit this in the future, but close this thread for now.

Thanks!
