### ISSUE TITLE
[Suggestion] Remove `html` type from CSS selectors.

### ISSUE THREAD

**Issue by kybradeck** [gmrchk/swup#90]
To define transitions, the readme specifies using the pattern `html.is-animating`, `html.is-leaving`, and similar constructs.

However, CSS selectors attached to element types cause issues with over-specificity: they will take precedence over selectors which do *not* include the element type, no matter how deep those selectors may be nested, leading to `!important` declarations or additional over-specific selectors to combat the original culprit.

I suggest removing `html` from the CSS, leaving `.is-animating`, `.is-leaving`, etc. as class names only. However, this could potentially conflict with 3rd party libraries that use the same class names, since they are common. I can imagine two solutions:

1. Prepend `swup-` to existing document-level classes. (So `.is-animating` becomes `.swup-is-animating`, `.is-leaving` becomes `.swup-is-leaving`.) This benefits from clarity: unfamiliar users would be able to immediately understand what library is responsible for adding the classes. It would leave the existing structure intact. However, it would break installations for any users who upgraded—they would have to update their class names.

2. Add a `.swup` class at the document level and combine that with existing classes. (`.is-animating` becomes `.swup.is-animating`, `.is-leaving` becomes `.swup.is-leaving`.) This contains the benefits above, but without breaking existing installations. It could potentially cause issues if the class `.swup` is used elsewhere (unclear) but otherwise I think it would help solve the issue with over-specificity.

**Comment by gmrchk** [comment]
Readme states this format for the sole purpose of repeating that the classes are applied to the html tag. Web beginners or people new to swup often overlook little details in the documentation, so repeating things where possible turned out to be helpful over time. The styles are also more specific, as you mentioned, which is generally bad... but I see that as a plus for less skilled users. 

I usually use something like the following pattern in stylus.

```stylus
.transition-fade
    opacity 1
    transition .4s

    .is-animating &
        opacity 0
```

I use libraries very rarely, and when I do, I know that they are not going to cause any trouble with swup, so this pattern is just fine for me. I'm also used to keeping the structure pretty flat (minimal nested classes, usually each element has its own class... classic BEM stuff), so overwriting styles is easy.

I'm sure that more skilled users have no problem figuring out how to best structure their CSS once they are familiar with how swup works, as you did as well. For the less skilled users, I think it's better to keep the `html.is...` recommendation in place.  

FYI - swup applies a class to the html tag at the start in a form of `swup-enabled`. The purpose of this class is to be able to restyle elements in case swup fails to run (similar to the common usage of js/no-js classes on the same tag. You can also use this class in your styles as you suggested in point 2.

**Comment by kybradeck** [comment]
That makes a lot of sense. I like your way of structuring CSS with the `&` parent selector. :)

Since swup makes other assumptions about the required format for CSS and I had run into trouble getting that working, I worried that `html` was there specifically *to* override other classes, and that removing it could pose unknown problems. I'm glad that it doesn't!

**Comment by gmrchk** [comment]
The functionality of the styles is similar to hover for example (describing different styles of the same element in some particular state), which most people probably define as `&:hover` with preprocessors, so I think it kinda makes sense to use a similar nesting technique. :)

Anyways, thanks for pitching some ideas!
