### ISSUE TITLE
Swup Working with Other Scripts

### ISSUE THREAD

**Issue by garethjohnsdesign** [gmrchk/swup#91]
First of all thanks for your work on this, is really interesting.
I'm trying to get the code to work but it doesn't seem to be loading when I introduce any other scripts

I have a working simple version here:
https://5c1782554e804d00081b507c--hotfeet.netlify.com

However as soon as I try to introduce other scripts it seems to break, in this example I'm trying to introduce Jquery and Foundation, it fades out but then just doesn't load back in

https://5c1785454e804d00081b5515--hotfeet.netlify.com

The code is here, but not really sure what I'm doing wrong
https://github.com/garethjohnsdesign/hotfeet.co/tree/swup

I tried to simplify as much as possible to rule out other scripts interfering but my Javascript knowledge is fairly limited

**Comment by gmrchk** [comment]
Hi @garethjohnsdesign,

The issue you are having is caused by overlapping classes used by swup and one of your scripts. In particular, the script used for opening the menu uses a class `is-transition-overlap`. Thanks to this class, swup registers that element as an element it needs to wait to finish the animation.

This can happen and for that reason, swup has an [animation selector](https://github.com/gmrchk/swup#animation-selector) option which allows making the animation selector more strict.

```javascript
var swup = new Swup({
    animationSelector: '[class*="swup-transition-"]'
});
```

The example above makes swup register only elements with class `swup-transition-[anything]`, which will solve your issue. You also need to reflect this change in your CSS and HTML.

```css
.swup-transition-fade {
    transition: .4s;
    opacity: 1;
}
html.is-animating .swup-transition-fade{
    opacity: 0;
}
```

```html
<main id="swup" class="swup-transition-fade">
    ...
</main>
```

**Comment by garethjohnsdesign** [comment]
You were correct here, as I mentioned I'm not so hot on script so didn't see the issue. Foundation uses the is-transition-overlap class, which was the problem

**Comment by gmrchk** [comment]
I have added your issue into [common issues](https://github.com/gmrchk/swup/wiki/Common-Issues), in case someone runs into a similar problem.

Thank you for reporting and creating great demos.
